name: Releases

on: 
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Create Release
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: NadeemYaseen/createTagRelease@main     
      with:
        repo: RaptorBuilds
        owner: os-fpga
        token: ${{ secrets.UPLOAD }}
        tag_name: ${{ github.sha }}
        release_name: build_${{ github.sha }}
